name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Generate Playwright Report
      run: |
        # Example command to generate a report (adjust as per your needs)
        npx playwright test --reporter=list
        # Ensure the report is generated in the playwright-report/ directory
        mkdir -p playwright-report
        # Move or copy the generated report files to playwright-report/
        # For example, if files are generated in a different directory, use:
        # mv generated-reports/* playwright-report/
        # Replace `generated-reports` with the actual directory containing reports
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
